import './global.css';
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

const inter = Inter({
  subsets:['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className='dark' lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
